spring:
  data:
    mongodb:
      uri: mongodb+srv://shrutisharma6369:gy5vFC1d8p9QSucX@cluster0.7o2ryxv.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      database: journaldb
      auto-index-creation: true
  mail:
    host: smtp.gmail.com
    port: 587
    userName: shrutisharma6369@gmail.com
    password: xhmg mnul molo takj
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true


server:
  port: 8081
  servlet:
    context-path: /journal

weather:
  api:
    key: 7a36778263625ccffebb1aa74f8fc363

